= Acey Duecy

By Lia Crocker and K. Humberto Lopez Felix


Use acey_duecy.py to play a card game of Acey Duecy. The game is played by dealing two cards and placing bets on the next card drawn being between the two cards on the table. If the third card dealt is between the first two drawn, the players have their bets matched by the bank. If the third card dealt is not between the first two, the players lose their bets to the bank.

The parameters to the program are:

* `players` : string of player names or name of the text file containing the names of the players
* `-b|--bank`: the starting amount of money in the bank (default: 10)
* `-m|--money`: the starting amount of money for each player (default: 10)
* `-s|--seed` : a random seed to use in testing (default: None)

----
$ ./acey_duecy.py -h
usage: acey_duecy.py [-h] [-b int] [-m int] [-s seed] str [str ...]

Play a game of Acey Duecy

positional arguments:
  str                   Player names text or file

optional arguments:
  -h, --help            show this help message and exit
  -b int, --bank int    Start value of bank (default: 10)
  -m int, --money int   Start value for players (default: 10)
  -s seed, --seed seed  Random Seed (default: None)
----					

If successful, report two cards from a single standard 52 card deck that were dealt and await user input for each player to place their bets.

----
$ ./acey_duecy.py Lia Humberto
  A "3 of Clubs" and an "Ace of Diamonds" are on the table.
  Players please place your bets.
  Lia: 
----

The program calls the players by name requesting their bets. The player Lia goes first. Lia enters her value and then it asks for input from Humberto.

----
$ ./acey_duecy.py Lia Humberto
  A "3 of Clubs" and an "Ace of Diamonds" are on the table.
  Players please place your bets.
  Lia: 1
  Humberto:
----

The program waits for Humberto to input an integer as his bet. Since Humberto is the last player, the third card is dealt after he inputs his bet. The program also reports new balance of each player and the bank. Then the program will ask the user if the players want to continue to the next round. If yes, a new round will begin and keep track of scores from previous rounds. If no, the program will end and the game will be erased.

----
$ ./acey_duecy.py Lia Humberto
  A "3 of Clubs" and an "Ace of Diamonds" are on the table.
  Players please place your bets.
  Lia: 1
  Humberto: 2
  
  The dealer places a "2 of Hearts" on the table!
  
  Bank: 7
  Lia: 11
  Humberto: 12
  
  Next round? (y/n)
----

== Test

A passing test suite looks like this:

----
$ make test
pytest --disable-pytest-warnings -xv test.py
============================= test session starts ==============================
...
collected 8 items

test.py::test_exists PASSED                                              [ 12%]
test.py::test_usage PASSED                                               [ 25%]
test.py::test_players PASSED                                             [ 37%]
test.py::test_money PASSED                                               [ 50%]
test.py::test_bets PASSED                                                [ 62%]
test.py::test_winning PASSED                                             [ 75%]
test.py::test_losing PASSED                                              [ 87%]
test.py::test_ending PASSED                                              [100%]

========================= 8 passed, 1 warning in 5.79s =========================
----
