= Acey Duecy

By Lia Crocker and K. Humberto Lopez Felix


Use acey_duecy.py to play a card game of Acey Duecy. The game is played by dealing two cards and placing bets on the next card drawn being between the two cards on the table. If the third card dealt is between the first two drawn, the players have their bets matched by the bank. If the third card dealt is not between the first two, the players lose their bets to the bank.

The parameters to the program are:

* `players` : string of player names or name of the text file containing the names of the players
* `-b|--bank`: the starting amount of money in the bank (default: 10)
* `-m|--money`: the starting amount of money for each player (default: 10)
* `-s|--seed` : a random seed to use in testing (default: None)

----
$ ./acey_duecy.py -h
usage: acey_duecy.py [-h] [-b int] [-m int] [-s seed] str [str ...]

Play a game of Acey Duecy

positional arguments:
  str                   Player names text or file

optional arguments:
  -h, --help            show this help message and exit
  -b int, --bank int    Start value of bank (default: 10)
  -m int, --money int   Start value for players (default: 10)
  -s seed, --seed seed  Random Seed (default: None)
----					

If successful, report two cards from a single standard 52 card deck that were dealt and await user input asking if the player would like to keep or change their card for a new one.

----
$ ./acey_duecy.py Lia Humberto
  {'Bank': 10}
  {'Lia': 10, 'Humberto': 10}
  Lia your card is a "6 of Clubs" and the dealer's card is a "5 of Clubs".
  Would you like to change or keep your card? (Type change or keep):
   
----

If the player chooses to change their card, a new card is drawn. If the player chooses to keep their card, the program asks for their bet.

----
$ ./acey_duecy.py Lia Humberto
  {'Bank': 10}
  {'Lia': 10, 'Humberto': 10}
  Lia your card is a "6 of Clubs" and the dealer's card is a "5 of Clubs".
  Would you like to change or keep your card? (Type change or keep): change
  Your new card is a "10 of Clubs".
  Please, place your bet:
   
----

The program waits for the player to input their bet and then gives the results of that round and moves on to the next player.

----
$ ./acey_duecy.py Lia Humberto
  {'Bank': 10}
  {'Lia': 10, 'Humberto': 10}
  Lia your card is a "6 of Clubs" and the dealer's card is a "5 of Clubs".
  Would you like to change or keep your card? (Type change or keep): change
  Your new card is a "10 of Clubs".
  Please, place your bet: 3

  The dealer places a "7 of Clubs" on the table!
  The third face-up card is between the first two face-up cards.
  YOU WIN!!!
  You win 3 chips in this round.
   
  {'Bank': 7}
  {'Lia': 13, 'Humberto': 10}
  Humberto your card is an "11 of Hearts" and the dealer's card is a "6 of Spades".
  Would you like to change or keep your card? (Type change or keep):
----

The program also reports the new balance of each player and the bank. If a player loses all their chips, they cannot possibly win, so they are eliminated from the game.

----
$ ./acey_duecy.py Lia Humberto -s 1
  ...
  Oooooooooh no!!! Lia does not have money and is out of the game
  {'Bank': 5}
  {'Lia': 0, 'Humberto': 15}
  Humberto your card is a "7 of Hearts" and the dealer's card is a "4 of Hearts".
  Would you like to change or keep your card? (Type change or keep):
----

If the bank is empty or all players except for one are eliminated, the game is over and a message is displayed.

----
$ ./acey_duecy.py Lia Humberto -s 1
  {'Bank': 10}
  {'Lia': 10, 'Humberto': 10}
  Lia your card is a "14 of Hearts" and the dealer's card is a "10 of Diamonds".
  Would you like to change or keep your card? (Type change or keep): keep
  Please, place your bet: 0

  The dealer places a "14 of Clubs" on the table!
  The third face-up card matches with one of the first two.
  YOU LOSE!!!
  You lose 0 chips in this round

  {'Bank': 10}
  {'Lia': 10, 'Humberto': 10}
  Humberto your card is a "9 of Hearts" and the dealer's card is a "14 of Diamonds".
  Would you like to change or keep your card? (Type change or keep): change
  Your new card is a "2 of Hearts".
  Please, place your bet: 20

  The dealer places a "7 of Spades" on the table!
  The third face-up card is between "2 of Hearts" and "14 of Diamonds".
  YOU WIN!!!
  You win 10 chips in this round.

  GAME OVER!
  Final Scores: {'Lia': 10, 'Humberto': 20}
----

The dialog accounts for matching the correct article (a/an) to the card that is drawn. The game also has some special cases of winning and losing. If the first two cards are consecutive, the player will lose. If the third card drawn is the same as either of the first two cards, the player will lose. If the first two cards are the same card, the player wins their bet plus two. 

== Test

A passing test suite looks like this:

----
$ make test
pytest --disable-pytest-warnings -xv test.py
============================= test session starts ==============================
...
collected 8 items

test.py::test_exists PASSED                                              [ 12%]
test.py::test_usage PASSED                                               [ 25%]
test.py::test_players PASSED                                             [ 37%]
test.py::test_money PASSED                                               [ 50%]
test.py::test_bets PASSED                                                [ 62%]
test.py::test_winning PASSED                                             [ 75%]
test.py::test_losing PASSED                                              [ 87%]
test.py::test_ending PASSED                                              [100%]

========================= 8 passed, 1 warning in 5.79s =========================
----
